### PR TITLE
Fix state reverting

### LINKED ISSUE #297: TaskHandler state can be reset after error
`.endOrError` should be terminal state

### PR DESCRIPTION
**Pull request by artemredkin**
Prevent TaskHandler state change after `.endOrError`
    
Motivation:
Right now if task handler encounters an error, it changes state to `.endOrError`. We gate on that state to make sure that we do not process errors in the pipeline twice. Unfortunately, that state can be reset when we upload body or receive response parts.
    
Modifications:
Adds state validation before state is updated to a new value
Adds a test
    
Result:
Fixes #297

### CODE REVIEW

File: Sources/AsyncHTTPClient/HTTPHandler.swift [hunk 1]
```diff
@@ -924,23 +934,28 @@ extension TaskHandler: ChannelDuplexHandler {
         let response = self.unwrapInboundIn(data)
         switch response {
         case .head(let head):
-            if !head.isKeepAlive {
-                self.closing = true
-            }
+            switch self.state {
```
Comment (Lukasa) [inline Sources/AsyncHTTPClient/HTTPHandler.swift:937]: This may read more clearly as:

```swift
if case .endOrError = self.state {
    return
}
```

Rather than forcing the indentation of the rest of the body.

File: Sources/AsyncHTTPClient/HTTPHandler.swift [hunk 2]
```diff
@@ -839,18 +839,28 @@ extension TaskHandler: ChannelDuplexHandler {
...
-                self.errorCaught(context: context, error: error)
-                return context.eventLoop.makeFailedFuture(error)
+            switch self.state {
+            case .endOrError:
+                return context.eventLoop.makeSucceededFuture(())
+            default:
+                self.state = .bodySent
+                if let expectedBodyLength = self.expectedBodyLength, expectedBodyLength != self.actualBodyLength {
+                    let error = HTTPClientError.bodyLengthMismatch
+                    self.errorCaught(context: context, error: error)
```
Comment (Lukasa) [inline Sources/AsyncHTTPClient/HTTPHandler.swift:850]: We don't need `errorCaught` here: the future chain will call this code path anyway.

**Review by Lukasa — COMMENTED** [review]
Broadly looks good, I've left a couple of notes in the diff.

File: Sources/AsyncHTTPClient/HTTPHandler.swift (hunk 1 above)
Comment (artemredkin) [reply Sources/AsyncHTTPClient/HTTPHandler.swift:934]: ah! thank you, always forget about this pattern

File: Sources/AsyncHTTPClient/HTTPHandler.swift (hunk 2 above)
Comment (artemredkin) [reply Sources/AsyncHTTPClient/HTTPHandler.swift]: fixed, thanks!

File: Sources/AsyncHTTPClient/HTTPHandler.swift (hunk 1 above)
Comment (Lukasa) [reply Sources/AsyncHTTPClient/HTTPHandler.swift:934]: Seems like the only place you didn't apply this pattern was this block? :wink:

Comment (artemredkin) [reply Sources/AsyncHTTPClient/HTTPHandler.swift]: 😅

**Review by Lukasa — APPROVED** [review]
Love it, looks great.
