### PR TITLE
Fix crash if connection is closed very early

### LINKED ISSUE #670: Fatal error: 'try!' expression unexpectedly raised an error: NIOCore.ChannelPipelineError.notFound
Vapor version : 4.69.2
OS: ubuntu 20.04

<pre>
AsyncHTTPClient/HTTPConnectionPool+Factory.swift:366: Fatal error: 'try!' expression unexpectedly raised an error: NIOCore.ChannelPipelineError.notFound
Current stack trace:
0    libswiftCore.so                    0x00007fac387e4930 _swift_stdlib_reportFatalErrorInFile + 112
1    libswiftCore.so                    0x00007fac384af8ec <unavailable> + 1444076
2    libswiftCore.so                    0x00007fac384af708 <unavailable> + 1443592
3    libswiftCore.so                    0x00007fac384ae1f0 _assertionFailure(_:_:file:line:flags:) + 419
4    libswiftCore.so                    0x00007fac385030b0 swift_unexpectedError + 748
5    dx_3                               0x00005576644b348c <unavailable> + 3847308
6    dx_3                               0x0000557664d92712 <unavailable> + 13149970
7    dx_3                               0x0000557664d92e63 <unavailable> + 13151843
8    dx_3                               0x0000557664d95ecc <unavailable> + 13164236
9    dx_3                               0x00005576650a5088 <unavailable> + 16371848
10   dx_3                               0x00005576650a7ec0 <unavailable> + 16383680
11   dx_3                               0x000055766509de52 <unavailable> + 16342610
12   dx_3                               0x00005576650a33fc <unavailable> + 16364540
13   dx_3                               0x0000557665063a37 <unavailable> + 16103991
14   dx_3                               0x000055766506411d <unavailable> + 16105757
15   dx_3                               0x00005576650698fc <unavailable> + 16128252
16   dx_3                               0x00005576650dca9f <unavailable> + 16599711
17   dx_3                               0x00005576650df5d2 <unavailable> + 16610770
18   dx_3                               0x00005576650df6d9 <unavailable> + 16611033
19   libpthread.so.0                    0x00007fac38abb609 <unavailable> + 34313
20   libc.so.6                          0x00007fac380220f0 clone + 67
Received signal 4. Backtrace:
0x5576648215bf, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /root/dx_3/x-bot/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66
0x5576648218e9, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /root/dx_3/x-bot/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:80
0x557664821908, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /root/dx_3/x-bot/<compiler-generated>:0
0x7fac38ac741f
0x7fac384ae39f
0x7fac3850339b
0x5576644b348b, closure #2 @Sendable (NIOCore.Channel) -> NIOCore.EventLoopFuture<(NIOCore.Channel, Swift.Optional<Swift.String>)> in AsyncHTTPClient.HTTPConnectionPool.ConnectionFactory.(makeTLSChannel in _AE48F78949F7DE5CB0E8AD63B3EC3A4B)<A where A: AsyncHTTPClient.HTTPConnectionRequester>(requester: A, connectionID: Swift.Int, deadline: NIOCore.NIODeadline, eventLoop: NIOCore.EventLoop, logger: Logging.Logger) -> NIOCore.EventLoopFuture<(NIOCore.Channel, Swift.Optional<Swift.String>)> at /root/dx_3/x-bot/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift:366
0x557664d92711, closure #1 @Sendable () -> NIOCore.CallbackList in NIOCore.EventLoopFuture._flatMap<A>(@Sendable (A) -> NIOCore.EventLoopFuture<A1>) -> NIOCore.EventLoopFuture<A1> at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:525
0x557664d92e62, NIOCore.EventLoopFuture._addCallback(@Sendable () -> NIOCore.CallbackList) -> NIOCore.CallbackList at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:935
0x557664d95ecb, closure #1 @Sendable () -> () in NIOCore.EventLoopFuture._internalWhenComplete(@Sendable () -> NIOCore.CallbackList) -> () at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:962
0x5576650a5087, closure #4 () -> () in NIOPosix.SelectableEventLoop.run() throws -> () at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:533
0x5576650a7ebf, partial apply forwarder for closure #4 () -> () in NIOPosix.SelectableEventLoop.run() throws -> () at /root/dx_3/x-bot/<compiler-generated>:0
0x55766509de51, NIOPosix.withAutoReleasePool<A>(() throws -> A) throws -> A at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:29
0x5576650a33fb, NIOPosix.SelectableEventLoop.run() throws -> () at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:532
0x557665063a36, static NIOPosix.MultiThreadedEventLoopGroup.(runTheLoop in _C2B1528F4FBA68A3DBFA89DBAEBE9D4D)(thread: NIOPosix.NIOThread, parentGroup: Swift.Optional<NIOPosix.MultiThreadedEventLoopGroup>, canEventLoopBeShutdownIndividually: Swift.Bool, selectorFactory: () throws -> NIOPosix.Selector<NIOPosix.NIORegistration>, initializer: (NIOPosix.NIOThread) -> (), _: (NIOPosix.SelectableEventLoop) -> ()) -> () at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:95
0x55766506411c, closure #1 (NIOPosix.NIOThread) -> () in static NIOPosix.MultiThreadedEventLoopGroup.(setupThreadAndEventLoop in _C2B1528F4FBA68A3DBFA89DBAEBE9D4D)(name: Swift.String, parentGroup: NIOPosix.MultiThreadedEventLoopGroup, selectorFactory: () throws -> NIOPosix.Selector<NIOPosix.NIORegistration>, initializer: (NIOPosix.NIOThread) -> ()) -> NIOPosix.SelectableEventLoop at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:116
0x5576650698fb, partial apply forwarder for closure #1 (NIOPosix.NIOThread) -> () in static NIOPosix.MultiThreadedEventLoopGroup.(setupThreadAndEventLoop in _C2B1528F4FBA68A3DBFA89DBAEBE9D4D)(name: Swift.String, parentGroup: NIOPosix.MultiThreadedEventLoopGroup, selectorFactory: () throws -> NIOPosix.Selector<NIOPosix.NIORegistration>, initializer: (NIOPosix.NIOThread) -> ()) -> NIOPosix.SelectableEventLoop at /root/dx_3/x-bot/<compiler-generated>:0
0x5576650dca9e, reabstraction thunk helper from @escaping @callee_guaranteed (@guaranteed NIOPosix.NIOThread) -> () to @escaping @callee_guaranteed (@in_guaranteed NIOPosix.NIOThread) -> (@out ()) at /root/dx_3/x-bot/<compiler-generated>:0
0x5576650df5d1, closure #1 (Swift.Optional<Swift.UnsafeMutableRawPointer>) -> Swift.Optional<Swift.UnsafeMutableRawPointer> in static NIOPosix.ThreadOpsPosix.run(handle: inout Swift.Optional<Swift.UInt>, args: NIOPosix.Box<(body: (NIOPosix.NIOThread) -> (), name: Swift.Optional<Swift.String>)>, detachThread: Swift.Bool) -> () at /root/dx_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/ThreadPosix.swift:105
0x5576650df6d8, @objc closure #1 (Swift.Optional<Swift.UnsafeMutableRawPointer>) -> Swift.Optional<Swift.UnsafeMutableRawPointer> in static NIOPosix.ThreadOpsPosix.run(handle: inout Swift.Optional<Swift.UInt>, args: NIOPosix.Box<(body: (NIOPosix.NIOThread) -> (), name: Swift.Optional<Swift.String>)>, detachThread: Swift.Bool) -> () at /root/dx_3/x-bot/<compiler-generated>:0
0x7fac38abb608
0x7fac38022132
0xffffffffffffffff
</pre>

### PR DESCRIPTION
**Pull request by dnadoba**
If the channel is closed before flatMap is executed, all ChannelHandler are removed and `TLSEventsHandler` is therefore not present either. We need to tolerate this even though it is very rare.

Testing ideas welcome.

Fixes #670

### CODE REVIEW

File: Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift [hunk 1]
```diff
@@ -361,14 +361,19 @@ extension HTTPConnectionPool.ConnectionFactory {
...
+                // and TLSEventsHandler is therefore not present either
+                let tlsEventHandler = try channel.pipeline.syncOperations.handler(type: TLSEventsHandler.self)
+                
+                // The tlsEstablishedFuture is set as soon as the TLSEventsHandler is in a
+                // pipeline. It is created in TLSEventsHandler's handlerAdded method.
+                return tlsEventHandler.tlsEstablishedFuture!.flatMap { negotiated in
+                    channel.pipeline.removeHandler(tlsEventHandler).map { (channel, negotiated) }
+                }
+            } catch {
+                precondition(channel.isActive == false, "if the channel is still active then TLSEventsHandler must be present but got error \(error)")
```
Comment (Lukasa) [inline Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift:375]: I don't think this precondition is particularly wise: the connection pool will appropriately handle this. Let's drop it to `assert` instead.

**Review by Lukasa — CHANGES_REQUESTED** [review]

File: Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift (hunk 1 above)
Comment (dnadoba) [reply Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift]: Done in [d0d1cee](https://github.com/swift-server/async-http-client/pull/671/commits/d0d1cee09e56b1c34758b270a5da99114903b6cc)

**Review by Lukasa — APPROVED** [review]

**Comment by Lukasa** [comment]
Can you clean up soundness?
