### PR TITLE
Fix leaked TLS handshake promise

### LINKED ISSUE #179: Leaking promise created at ConnectionPool.swift line 373
Hi,

I just checked out the current master commit `9cdd1dc` and wanted to test it with my [lambda-runtime](https://github.com/fabianfett/swift-lambda-runtime).

When building for macOS in DEBUG, I ran immediately into a fatalError:

```
Fatal error: leaking promise created at (file: "/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-brfbdomqotikxpeqafasrajmegus/SourcePackages/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool.swift", line: 373): file /Users/xxx/Library/Developer/Xcode/DerivedData/xxx-brfbdomqotikxpeqafasrajmegus/SourcePackages/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool.swift, line 373
```

This happens on the first invocation of `execute`.

I haven't found a similar issue here, so that's why I created one.

### PR DESCRIPTION
**Pull request by adtrevor**
motivation:
TLS handshake promise was leaked in some cases of failure (fixes #179)

changes:
- Avoid leaking promise
- Clearer completion flow for related futures
- Add testAvoidLeakingTLSHandshakeCompletionPromise test

### CODE REVIEW

File: Sources/AsyncHTTPClient/ConnectionPool.swift [hunk 1]
```diff
@@ -383,32 +383,33 @@ final class ConnectionPool {
             }
 
             return channel.flatMap { channel -> EventLoopFuture<ConnectionPool.Connection> in
-                channel.pipeline.addSSLHandlerIfNeeded(for: self.key, tlsConfiguration: self.configuration.tlsConfiguration, handshakePromise: handshakePromise).flatMap {
+                channel.pipeline.addSSLHandlerIfNeeded(for: self.key, tlsConfiguration: self.configuration.tlsConfiguration, handshakePromise: handshakePromise)
```
Comment (adtrevor) [inline Sources/AsyncHTTPClient/ConnectionPool.swift]: The promise *and* returned future were redundant IMO so this only makes use of `handshakePromise` now

File: Tests/AsyncHTTPClientTests/HTTPClientTests.swift [hunk 2]
```diff
@@ -1656,4 +1656,17 @@ class HTTPClientTests: XCTestCase {
             Thread.sleep(forTimeInterval: 0.01 + .random(in: -0.05...0.05))
         }
     }
+
+    func testAvoidLeakingTLSHandshakeCompletionPromise() {
+        let httpClient = HTTPClient(eventLoopGroupProvider: .createNew)
+        defer {
+            XCTAssertNoThrow(try httpClient.syncShutdown(requiresCleanClose: true))
+        }
+        XCTAssertThrowsError(try httpClient.get(url: "http://localhost/").wait()) { error in
```
Comment (weissi) [inline Tests/AsyncHTTPClientTests/HTTPClientTests.swift]: this test isn't great. It relies on nothing being bound to port 80 on `localhost`. Can I suggest a slightly different strategy: Let's bind a random port with a server socket, then immediately close it and then connect that port instead and we have pretty high confidence that this port won't be bound by something else

Comment (adtrevor) [reply Tests/AsyncHTTPClientTests/HTTPClientTests.swift]: @weissi Thank you! In https://github.com/swift-server/async-http-client/commit/cfba7e762d7faef23e42f66a438b538436ba973c, the  `refusesConnections: true` option is now set on `HTTPBin`, I think it gives the behaviour we want?

Comment (adtrevor) [reply Tests/AsyncHTTPClientTests/HTTPClientTests.swift]: Oops actually I don't think it does, I must still close it because the connection is still accepted it seems

Comment (adtrevor) [reply Tests/AsyncHTTPClientTests/HTTPClientTests.swift]: @weissi Latest push should be ok 🙂
