### PR TITLE
fix test faling with NIOTS

### LINKED ISSUE #256: tests fail on macOS
```
Test Case '-[AsyncHTTPClientTests.HTTPClientInternalTests testUncleanCloseThrows]' started.
Fatal error: ServerBootstrap is only compatible with MultiThreadedEventLoopGroup and SelectableEventLoop. You tried constructing one with NIOTransportServices.NIOTSEventLoop which is incompatible.: file /Users/johannes/devel/swift-nio/Sources/NIO/Bootstrap.swift, line 87
Exited with signal code 4
```

### PR DESCRIPTION
**Pull request by artemredkin**
Fixes test crashing on precondition.

Motivation:
When tests are executed on macOS client ELG is actually a `NIOTS` ELG, so it's incompatible with `NIOHTTP1TestServer`

Modifications:
Use separate ELG in `testUncleanCloseThrows`

Result:
Closes #256

### CODE REVIEW

File: Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift [hunk 1]
```diff
@@ -797,7 +797,7 @@ class HTTPClientInternalTests: XCTestCase {
     }
 
     func testUncleanCloseThrows() {
-        let server = NIOHTTP1TestServer(group: self.clientGroup)
+        let server = NIOHTTP1TestServer(group: MultiThreadedEventLoopGroup(numberOfThreads: 1))
```
Comment (weissi) [inline Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift:800]: who shuts this MTELG down?

Comment (weissi) [reply Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift:800]: I think we have `self.serverGroup` which could be used

Comment (artemredkin) [reply Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift:800]: oooops, no one, good catch, thank you! no, we don't have that in internal tests class

Comment (artemredkin) [reply Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift]: and its only monday... 😔

Comment (weissi) [reply Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift]: > oooops, no one, good catch, thank you! no, we don't have that in internal tests class

We should. I was probably lazy and changed only all of the non-internal tests

Comment (artemredkin) [reply Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift]: so far we won't be using it anywhere else in that class (it usually just creates `HTTPBin`), still worth it?

Comment (weissi) [reply Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift]: @artemredkin I think we should have a `defaultHTTPBin` and `defaultClient` and `client/serverGroup` all set up in `setUp`/`tearDown`. That makes tests more concise and therefore better

Comment (weissi) [reply Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift]: but we don't need to do it right in this PR, up to you
