### PR TITLE
fix flaky testContentLengthTooLongFails test

### LINKED ISSUE #265: flaky test HTTPClientTests.testContentLengthTooLongFails
```
Test Case 'HTTPClientTests.testContentLengthTooLongFails' started at 2020-06-16 19:10:55.784
/code/Tests/AsyncHTTPClientTests/HTTPClientTests.swift:2323: error: HTTPClientTests.testContentLengthTooLongFails : XCTAssertThrowsError failed: did not throw error - 
/code/Tests/AsyncHTTPClientTests/HTTPClientTests.swift:2338: error: HTTPClientTests.testContentLengthTooLongFails : failed - Body missing: Response(host: "localhost", status: NIOHTTP1.HTTPResponseStatus.badRequest, version: HTTP/1.1, headers: [("Connection", "close"), ("Content-Length", "0")], body: nil)
Test Case 'HTTPClientTests.testContentLengthTooLongFails' failed (0.046 seconds)
```

### PR DESCRIPTION
**Pull request by artemredkin**
Fixes flaky test

Motivation:
Test was actually getting `404` and was closing connection too early.

Modifications:
Fix request path.

Result:
Closes #265

### CODE REVIEW

File: Tests/AsyncHTTPClientTests/HTTPClientTests.swift [hunk 1]
```diff
@@ -2319,7 +2319,7 @@ class HTTPClientTests: XCTestCase {
     }
 
     func testContentLengthTooLongFails() throws {
-        let url = self.defaultHTTPBinURLPrefix + "/post"
+        let url = self.defaultHTTPBinURLPrefix + "post"
```
Comment (artemredkin) [inline Tests/AsyncHTTPClientTests/HTTPClientTests.swift:2322]: in `httpbin`:
```
URLComponents(string: "//post")!.percentEncodedPath -> ""
```

**Comment by artemredkin** [comment]
I almost pulled all my hair out trying to figure out why the channel is closed :)
