### PR TITLE
draft for streaming el fixes

### LINKED ISSUE #198: programming model: EventLoopPreference.delegate(on:) not respected for .stream
I'm not 100% sure if this counts as a bug but I think it should because it makes the programming model really hard.

If I configure

```
                let desiredEL = context.eventLoop // or some other EL I like
                let req = try HTTPClient.Request(url: url, method: req.method, headers: req.headers, body: .stream { _ in desiredEL.preconditionInEventLoop() })
                let task = self.httpClient.execute(request: req,
                                                   delegate: self,
                                                   eventLoop: .delegate(on: desiredEL))
```

this would fail as the closure passed to `.stream` isn't executed on `desiredEL`.

### LINKED ISSUE #200: StreamWriter expects to be called on some internal EventLoop
The `HTTPClient.Body.StreamWriter` that you get when using the default `.stream(length: contentLength, { thisStreamWriterHere in })` expects to be called on the internal `EventLoop` that belongs to the underlying `Channel`. The user however doesn't get access to that `Channel` at all so it's impossible to use this API :(.

This needs a fix really soon.

### PR DESCRIPTION
**Pull request by artemredkin**
Fixes programming model for upload streaming

Motivation:
Right now EL on which we execute streaming call back is not explicitly defined. Also, we do not check on which EL part write is executed, meaning we can fail if `.write` is not called on correct EL.

Modifications:
1. Call to `body.stream` is now executed on tasks EL
2. Calls to `writeAndFlush` are always called on channel EL
3. Added tests for those to cases
4. Removed a hack in test introduced in #219 
5. Fixed #219 shutdown to not call to shutdown EL

Result:
1. closes #198
2. closes #200

### CODE REVIEW

File: Sources/AsyncHTTPClient/HTTPHandler.swift [hunk 1]
```diff
@@ -765,12 +765,32 @@ extension TaskHandler: ChannelDuplexHandler {
             return context.eventLoop.makeSucceededFuture(())
         }
 
-        return body.stream(HTTPClient.Body.StreamWriter { part in
-            context.eventLoop.assertInEventLoop()
-            return context.writeAndFlush(self.wrapOutboundOut(.body(part))).map {
-                self.callOutToDelegateFireAndForget(value: part, self.delegate.didSendRequestPart)
+        func doIt() -> EventLoopFuture<Void> {
+            return body.stream(HTTPClient.Body.StreamWriter { part in
+                let promise = self.task.eventLoop.makePromise(of: Void.self)
```
Comment (weissi) [inline Sources/AsyncHTTPClient/HTTPHandler.swift:770]: this whole block should just be

```swift
return channel.writeAndFlush(HTTPClientRequestPart.body(part)).map {
    self.callOutToDelegateFireAndForget(value: part, self.delegate.didSendRequetsPart)
}
```

Comment (artemredkin) [reply Sources/AsyncHTTPClient/HTTPHandler.swift:770]: we only have access to `context` here, so in order to get to `channel` we have to call `context.channel` that is precondition on an being on channel EL, am I missing something?

Comment (artemredkin) [reply Sources/AsyncHTTPClient/HTTPHandler.swift:770]: actually, even if I get the channel, I cannot write `.part` to it since first handler in the channel expects `Request`
