### PR TITLE
All internal connection flow should be executed when shutting down

### LINKED ISSUE #260: flaky test: HTTPClientTests.testRaceNewRequestsVsShutdown stuck
on macOS

```
Call graph:
    2852 Thread_2604820   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2852 start  (in libdyld.dylib) + 1  [0x7fff6ec9ec71]
    +   2852 main  (in xctest) + 203  [0x10b975ef0]
    +     2852 _XCTestMain  (in XCTest) + 108  [0x10bae04c1]
    +       2852 -[XCTestDriver _runTests]  (in XCTest) + 466  [0x10ba3cea2]
    +         2852 -[XCTTestRunSession runTestsAndReturnError:]  (in XCTest) + 615  [0x10bb0040d]
    +           2852 -[XCTestObservationCenter _observeTestExecutionForBlock:]  (in XCTest) + 325  [0x10ba7fcc8]
    +             2852 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.95  (in XCTest) + 96  [0x10bb007c8]
    +               2852 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke  (in XCTest) + 111  [0x10bb00647]
    +                 2852 +[XCTContext runInContextForTestCase:block:]  (in XCTest) + 211  [0x10bae431d]
    +                   2852 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke_2  (in XCTest) + 148  [0x10bb006e2]
    +                     2852 -[XCTest runTest]  (in XCTest) + 57  [0x10bab148a]
    +                       2852 -[XCTestSuite performTest:]  (in XCTest) + 290  [0x10ba58db9]
    +                         2852 -[XCTestSuite _performProtectedSectionForTest:testSection:]  (in XCTest) + 148  [0x10ba58ab5]
    +                           2852 +[XCTContext runInContextForTestCase:block:]  (in XCTest) + 211  [0x10bae431d]
    +                             2852 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke  (in XCTest) + 24  [0x10ba58afe]
    +                               2852 __27-[XCTestSuite performTest:]_block_invoke  (in XCTest) + 329  [0x10ba592dd]
    +                                 2852 -[XCTest runTest]  (in XCTest) + 57  [0x10bab148a]
    +                                   2852 -[XCTestSuite performTest:]  (in XCTest) + 290  [0x10ba58db9]
    +                                     2852 -[XCTestSuite _performProtectedSectionForTest:testSection:]  (in XCTest) + 148  [0x10ba58ab5]
    +                                       2852 +[XCTContext runInContextForTestCase:block:]  (in XCTest) + 211  [0x10bae431d]
    +                                         2852 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke  (in XCTest) + 24  [0x10ba58afe]
    +                                           2852 __27-[XCTestSuite performTest:]_block_invoke  (in XCTest) + 329  [0x10ba592dd]
    +                                             2852 -[XCTest runTest]  (in XCTest) + 57  [0x10bab148a]
    +                                               2852 -[XCTestSuite performTest:]  (in XCTest) + 290  [0x10ba58db9]
    +                                                 2852 -[XCTestSuite _performProtectedSectionForTest:testSection:]  (in XCTest) + 148  [0x10ba58ab5]
    +                                                   2852 +[XCTContext runInContextForTestCase:block:]  (in XCTest) + 211  [0x10bae431d]
    +                                                     2852 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke  (in XCTest) + 24  [0x10ba58afe]
    +                                                       2852 __27-[XCTestSuite performTest:]_block_invoke  (in XCTest) + 329  [0x10ba592dd]
    +                                                         2852 -[XCTest runTest]  (in XCTest) + 57  [0x10bab148a]
    +                                                           2852 -[XCTestCase performTest:]  (in XCTest) + 690  [0x10ba5fa56]
    +                                                             2852 +[XCTContext runInContextForTestCase:block:]  (in XCTest) + 211  [0x10bae431d]
    +                                                               2852 __26-[XCTestCase performTest:]_block_invoke.362  (in XCTest) + 86  [0x10ba601e9]
    +                                                                 2852 -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:]  (in XCTest) + 179  [0x10bad33b0]
    +                                                                   2852 __26-[XCTestCase performTest:]_block_invoke_2  (in XCTest) + 43  [0x10ba602b2]
    +                                                                     2852 -[XCTestCase invokeTest]  (in XCTest) + 1037  [0x10ba5e8d9]
    +                                                                       2852 -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:]  (in XCTest) + 179  [0x10bad33b0]
    +                                                                         2852 __24-[XCTestCase invokeTest]_block_invoke.231  (in XCTest) + 199  [0x10ba5ee16]
    +                                                                           2852 -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:]  (in XCTest) + 61  [0x10ba698fa]
    +                                                                             2852 -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:]  (in XCTest) + 65  [0x10baedb5e]
    +                                                                               2852 __24-[XCTestCase invokeTest]_block_invoke_2  (in XCTest) + 297  [0x10ba5ef82]
    +                                                                                 2852 __24-[XCTestCase invokeTest]_block_invoke_3  (in XCTest) + 52  [0x10ba5efce]
    +                                                                                   2852 -[NSInvocation invoke]  (in CoreFoundation) + 303  [0x7fff2ee9b6ec]
    +                                                                                     2852 __invoking___  (in CoreFoundation) + 140  [0x7fff2ee9b84c]
    +                                                                                       2852 @objc HTTPClientTests.testRaceNewRequestsVsShutdown()  (in async-http-clientPackageTests) + 43  [0x1125b1d9b]  <compiler-generated>:0
    +                                                                                         2852 HTTPClientTests.testRaceNewRequestsVsShutdown()  (in async-http-clientPackageTests) + 3564  [0x1125b0bbc]  HTTPClientTests.swift:1175
    +                                                                                           2852 XCTAssertNoThrow<A>(_:_:file:line:)  (in libXCTestSwiftSupport.dylib) + 70  [0x10c2656b6]
    +                                                                                             2852 _XCTRunThrowableBlock(_:)  (in libXCTestSwiftSupport.dylib) + 208  [0x10c25d7d0]
    +                                                                                               2852 _XCTRunThrowableBlockBridge  (in libXCTestSwiftSupport.dylib) + 42  [0x10c259d7a]
    +                                                                                                 2852 thunk for @escaping @callee_guaranteed () -> ()  (in libXCTestSwiftSupport.dylib) + 14  [0x10c25d99e]
    +                                                                                                   2852 partial apply for thunk for @callee_guaranteed () -> ()  (in libXCTestSwiftSupport.dylib) + 17  [0x10c266101]
    +                                                                                                     2852 partial apply for closure #1 in _XCTRunThrowableBlock(_:)  (in libXCTestSwiftSupport.dylib) + 27  [0x10c2660ab]
    +                                                                                                       2852 partial apply for closure #1 in XCTAssertNoThrow<A>(_:_:file:line:)  (in libXCTestSwiftSupport.dylib) + 21  [0x10c265e15]
    +                                                                                                         2852 closure #1 in XCTAssertNoThrow<A>(_:_:file:line:)  (in libXCTestSwiftSupport.dylib) + 54  [0x10c265b66]
    +                                                                                                           2852 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply  (in async-http-clientPackageTests) + 20  [0x1125b1c94]  <compiler-generated>:0
    +                                                                                                             2852 thunk for @callee_guaranteed () -> (@error @owned Error)  (in async-http-clientPackageTests) + 15  [0x11245857f]  <compiler-generated>:0
    +                                                                                                               2852 partial apply for implicit closure #4 in HTTPClientTests.testRaceNewRequestsVsShutdown()  (in async-http-clientPackageTests) + 15  [0x1125b1c6f]  <compiler-generated>:0
    +                                                                                                                 2852 implicit closure #4 in HTTPClientTests.testRaceNewRequestsVsShutdown()  (in async-http-clientPackageTests) + 25  [0x1125b1c29]  <compiler-generated>:0
    +                                                                                                                   2852 HTTPClient.syncShutdown()  (in async-http-clientPackageTests) + 35  [0x112457983]  HTTPClient.swift:123
    +                                                                                                                     2852 HTTPClient.syncShutdown(requiresCleanClose:)  (in async-http-clientPackageTests) + 1121  [0x112457e21]  HTTPClient.swift:155
    +                                                                                                                       2852 DispatchWorkItem.wait()  (in libswiftDispatch.dylib) + 34  [0x7fff6e715dc2]
    +                                                                                                                         2852 dispatch_block_wait  (in libdispatch.dylib) + 212  [0x7fff6ec4b29f]
    +                                                                                                                           2852 _dispatch_group_wait_slow  (in libdispatch.dylib) + 49  [0x7fff6ec48acc]
    +                                                                                                                             2852 _dlock_wait  (in libdispatch.dylib) + 44  [0x7fff6ec48838]
    +                                                                                                                               2852 __ulock_wait  (in libsystem_kernel.dylib) + 10  [0x7fff6edff99e]
    2852 Thread_2605272: NIO-ELT-156-#0
    + 2852 thread_start  (in libsystem_pthread.dylib) + 15  [0x7fff6eec64d7]
    +   2852 _pthread_start  (in libsystem_pthread.dylib) + 224  [0x7fff6eeca9b4]
    +     2852 @objc closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:)  (in async-http-clientPackageTests) + 9  [0x112949b29]  <compiler-generated>:0
    +       2852 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:)  (in async-http-clientPackageTests) + 1256  [0x112949a58]  ThreadPosix.swift:105
    +         2852 partial apply for thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> ()  (in async-http-clientPackageTests) + 17  [0x1129430c1]  <compiler-generated>:0
    +           2852 thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> ()  (in async-http-clientPackageTests) + 15  [0x11287b79f]  <compiler-generated>:0
    +             2852 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:selectorFactory:initializer:)  (in async-http-clientPackageTests) + 51  [0x112881973]  <compiler-generated>:0
    +               2852 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:selectorFactory:initializer:)  (in async-http-clientPackageTests) + 355  [0x11287b193]  EventLoop.swift:842
    +                 2852 static MultiThreadedEventLoopGroup.runTheLoop(thread:canEventLoopBeShutdownIndividually:selectorFactory:initializer:_:)  (in async-http-clientPackageTests) + 972  [0x11287a9cc]  EventLoop.swift:822
    +                   2852 SelectableEventLoop.run()  (in async-http-clientPackageTests) + 928  [0x1128f89f0]  SelectableEventLoop.swift:394
    +                     2852 withAutoReleasePool<A>(_:)  (in async-http-clientPackageTests) + 57  [0x1128f4739]  SelectableEventLoop.swift:22
    +                       2852 autoreleasepool<A>(invoking:)  (in libswiftObjectiveC.dylib) + 46  [0x7fff6e92fb3e]
    +                         2852 partial apply for closure #1 in withAutoReleasePool<A>(_:)  (in async-http-clientPackageTests) + 31  [0x1128f47ef]  <compiler-generated>:0
    +                           2852 closure #1 in withAutoReleasePool<A>(_:)  (in async-http-clientPackageTests) + 34  [0x1128f4792]  SelectableEventLoop.swift:23
    +                             2852 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply  (in async-http-clientPackageTests) + 20  [0x1128fd8c4]  <compiler-generated>:0
    +                               2852 thunk for @callee_guaranteed () -> (@error @owned Error)  (in async-http-clientPackageTests) + 15  [0x11245857f]  <compiler-generated>:0
    +                                 2852 partial apply for closure #2 in SelectableEventLoop.run()  (in async-http-clientPackageTests) + 20  [0x1128fd8a4]  <compiler-generated>:0
    +                                   2852 closure #2 in SelectableEventLoop.run()  (in async-http-clientPackageTests) + 233  [0x1128f9d39]  SelectableEventLoop.swift:395
    +                                     2852 Selector.whenReady(strategy:_:)  (in async-http-clientPackageTests) + 1200  [0x11290c560]  Selector.swift:517
    +                                       2852 Optional.withUnsafeOptionalPointer<A>(_:)  (in async-http-clientPackageTests) + 561  [0x1128ff2c1]  Selector.swift:39
    +                                         2852 partial apply for thunk for @callee_guaranteed (@unowned UnsafePointer<timespec>?) -> (@unowned Int, @error @owned Error)  (in async-http-clientPackageTests) + 20  [0x112910db4]  <compiler-generated>:0
    +                                           2852 thunk for @callee_guaranteed (@unowned UnsafePointer<timespec>?) -> (@unowned Int, @error @owned Error)  (in async-http-clientPackageTests) + 19  [0x11290e873]  <compiler-generated>:0
    +                                             2852 partial apply for closure #1 in Selector.whenReady(strategy:_:)  (in async-http-clientPackageTests) + 15  [0x112910d8f]  <compiler-generated>:0
    +                                               2852 closure #1 in Selector.whenReady(strategy:_:)  (in async-http-clientPackageTests) + 499  [0x11290e773]  Selector.swift:518
    +                                                 2852 static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:)  (in async-http-clientPackageTests) + 377  [0x1129427c9]  System.swift:544
    +                                                   2852 syscall<A>(blocking:where:_:)  (in async-http-clientPackageTests) + 441  [0x11293b049]  System.swift:127
    +                                                     2852 thunk for @callee_guaranteed () -> (@unowned Int32, @error @owned Error)partial apply  (in async-http-clientPackageTests) + 20  [0x1129429b4]  <compiler-generated>:0
    +                                                       2852 thunk for @callee_guaranteed () -> (@unowned Int32, @error @owned Error)  (in async-http-clientPackageTests) + 19  [0x112545363]  <compiler-generated>:0
    +                                                         2852 closure #1 in static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:)  (in async-http-clientPackageTests) + 167  [0x112942947]  System.swift:545
    +                                                           2852 @nonobjc kevent(_:_:_:_:_:_:)  (in async-http-clientPackageTests) + 9  [0x11293a9a9]  <compiler-generated>:0
    +                                                             2852 kevent  (in libsystem_kernel.dylib) + 10  [0x7fff6ee02bba]
    2852 Thread_2605273: NIO-ELT-157-#0
    + 2852 thread_start  (in libsystem_pthread.dylib) + 15  [0x7fff6eec64d7]
    +   2852 _pthread_start  (in libsystem_pthread.dylib) + 224  [0x7fff6eeca9b4]
    +     2852 @objc closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:)  (in async-http-clientPackageTests) + 9  [0x112949b29]  <compiler-generated>:0
    +       2852 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:)  (in async-http-clientPackageTests) + 1256  [0x112949a58]  ThreadPosix.swift:105
    +         2852 partial apply for thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> ()  (in async-http-clientPackageTests) + 17  [0x1129430c1]  <compiler-generated>:0
    +           2852 thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> ()  (in async-http-clientPackageTests) + 15  [0x11287b79f]  <compiler-generated>:0
    +             2852 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:selectorFactory:initializer:)  (in async-http-clientPackageTests) + 51  [0x112881973]  <compiler-generated>:0
    +               2852 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:selectorFactory:initializer:)  (in async-http-clientPackageTests) + 355  [0x11287b193]  EventLoop.swift:842
    +                 2852 static MultiThreadedEventLoopGroup.runTheLoop(thread:canEventLoopBeShutdownIndividually:selectorFactory:initializer:_:)  (in async-http-clientPackageTests) + 972  [0x11287a9cc]  EventLoop.swift:822
    +                   2852 SelectableEventLoop.run()  (in async-http-clientPackageTests) + 928  [0x1128f89f0]  SelectableEventLoop.swift:394
    +                     2852 withAutoReleasePool<A>(_:)  (in async-http-clientPackageTests) + 57  [0x1128f4739]  SelectableEventLoop.swift:22
    +                       2852 autoreleasepool<A>(invoking:)  (in libswiftObjectiveC.dylib) + 46  [0x7fff6e92fb3e]
    +                         2852 partial apply for closure #1 in withAutoReleasePool<A>(_:)  (in async-http-clientPackageTests) + 31  [0x1128f47ef]  <compiler-generated>:0
    +                           2852 closure #1 in withAutoReleasePool<A>(_:)  (in async-http-clientPackageTests) + 34  [0x1128f4792]  SelectableEventLoop.swift:23
    +                             2852 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply  (in async-http-clientPackageTests) + 20  [0x1128fd8c4]  <compiler-generated>:0
    +                               2852 thunk for @callee_guaranteed () -> (@error @owned Error)  (in async-http-clientPackageTests) + 15  [0x11245857f]  <compiler-generated>:0
    +                                 2852 partial apply for closure #2 in SelectableEventLoop.run()  (in async-http-clientPackageTests) + 20  [0x1128fd8a4]  <compiler-generated>:0
    +                                   2852 closure #2 in SelectableEventLoop.run()  (in async-http-clientPackageTests) + 233  [0x1128f9d39]  SelectableEventLoop.swift:395
    +                                     2852 Selector.whenReady(strategy:_:)  (in async-http-clientPackageTests) + 1200  [0x11290c560]  Selector.swift:517
    +                                       2852 Optional.withUnsafeOptionalPointer<A>(_:)  (in async-http-clientPackageTests) + 561  [0x1128ff2c1]  Selector.swift:39
    +                                         2852 partial apply for thunk for @callee_guaranteed (@unowned UnsafePointer<timespec>?) -> (@unowned Int, @error @owned Error)  (in async-http-clientPackageTests) + 20  [0x112910db4]  <compiler-generated>:0
    +                                           2852 thunk for @callee_guaranteed (@unowned UnsafePointer<timespec>?) -> (@unowned Int, @error @owned Error)  (in async-http-clientPackageTests) + 19  [0x11290e873]  <compiler-generated>:0
    +                                             2852 partial apply for closure #1 in Selector.whenReady(strategy:_:)  (in async-http-clientPackageTests) + 15  [0x112910d8f]  <compiler-generated>:0
    +                                               2852 closure #1 in Selector.whenReady(strategy:_:)  (in async-http-clientPackageTests) + 499  [0x11290e773]  Selector.swift:518
    +                                                 2852 static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:)  (in async-http-clientPackageTests) + 377  [0x1129427c9]  System.swift:544
    +                                                   2852 syscall<A>(blocking:where:_:)  (in async-http-clientPackageTests) + 441  [0x11293b049]  System.swift:127
    +                                                     2852 thunk for @callee_guaranteed () -> (@unowned Int32, @error @owned Error)partial apply  (in async-http-clientPackageTests) + 20  [0x1129429b4]  <compiler-generated>:0
    +                                                       2852 thunk for @callee_guaranteed () -> (@unowned Int32, @error @owned Error)  (in async-http-clientPackageTests) + 19  [0x112545363]  <compiler-generated>:0
    +                                                         2852 closure #1 in static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:)  (in async-http-clientPackageTests) + 167  [0x112942947]  System.swift:545
    +                                                           2852 @nonobjc kevent(_:_:_:_:_:_:)  (in async-http-clientPackageTests) + 9  [0x11293a9a9]  <compiler-generated>:0
    +                                                             2852 kevent  (in libsystem_kernel.dylib) + 10  [0x7fff6ee02bba]
    2852 Thread_2993824
      2852 start_wqthread  (in libsystem_pthread.dylib) + 15  [0x7fff6eec64c3]
        2852 _pthread_wqthread  (in libsystem_pthread.dylib) + 414  [0x7fff6eec7556]
          2852 __workq_kernreturn  (in libsystem_kernel.dylib) + 10  [0x7fff6edff90e]

Total number in stack (recursive counted multiple, when >=5):
        5       +[XCTContext runInContextForTestCase:block:]  (in XCTest) + 211  [0x10bae431d]

Sort by top of stack, same collapsed (when >= 5):
        kevent  (in libsystem_kernel.dylib)        5704
        __ulock_wait  (in libsystem_kernel.dylib)        2852
        __workq_kernreturn  (in libsystem_kernel.dylib)        2852
```

lskq/of

```
$ lskq -p 77189
command                pid                 kq kqst               knid filter    fdtype   fflags       flags           evst      qos               data
-------------------- ----- ------------------ ---- ------------------ --------- -------- ------- --------------- -------------- --- ------------------
xctest               77189                 wq  --q                  0 MEMSTATUS                  an-- --cs u---- ----- ---- ---  UI                  0 
xctest               77189                 wq  --q                  0 MEMSTATUS                  an-- --cs u---- ----- ---- ---  IN                  0 
xctest               77189                 wq  --q                  0 MEMSTATUS                  an-- --cs u---- ----- ---- ---  MG                  0 
xctest               77189                 wq  --q                  1 USER               ---     a--- --c- ----- ----- ---- ---  MG                  0 
xctest               77189                 wq  --q             0x1303 MACHPORT           r       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189                 wq  --q             0x1a0b MACHPORT           r       an-- ---s u---- ----- ---- -v-  MG                  0 
xctest               77189                 wq  --q                147 PROC               x------ an-- --cs u---- ----- ---- ---  IN                  0 
xctest               77189                 wq  --q 0xffffffffffffff06 TIMER              na--l   an-- -1c- ----- ----- ---- ---  MG                  0 
xctest               77189 fd               7  ---                  6 WRITE     PIPE             an-- --c- ----- aq--- ---- ---  --                  0 
xctest               77189 fd               8  k--                  0 USER               ---     an-- --c- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 13 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 15 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 18 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 20 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 22 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 25 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 27 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                 28 READ      SOCKET   -       a--- ---- ----- ----- ---- ---  --                  0 
xctest               77189 fd              10  k--                  0 USER               ---     an-- --c- ----- ----- ---- ---  --                  0 
xctest               77189     0x7ff95b1043c0  --l             0x1103 MACHPORT           -       an-- ---s u---- ----- ---- -v-  IN                  0 
xctest               77189     0x7ff95852f260  --l             0x2707 MACHPORT           r       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff95b105700  --l                  5 READ      PIPE     l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958649f80  --l             0x33a3 MACHPORT           r       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 11 READ      POLICY   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 14 SOCK      SOCKET           an-- --cs u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 14 READ      SOCKET   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 17 SOCK      SOCKET           an-- --cs u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 17 READ      SOCKET   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 19 SOCK      SOCKET           an-- --cs u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 19 READ      SOCKET   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 21 SOCK      SOCKET           an-- --cs u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 21 READ      SOCKET   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 23 SOCK      SOCKET           an-- --cs u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 23 READ      SOCKET   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 24 SOCK      SOCKET           an-- --cs u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 24 READ      SOCKET   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 26 SOCK      SOCKET           an-- --cs u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l                 26 READ      SOCKET   l       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff958643210  --l 0xffffffffffffff03 TIMER              ma--l   an-- -1c- ----- ----- ---- ---  DF                  0 
xctest               77189     0x7ff95870ca60  --l             0x1903 MACHPORT           r       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff95b22a150  --l             0x5103 MACHPORT           r       an-- ---s u---- ----- ---- -v-  DF                  0 
xctest               77189     0x7ff95b104ab0  --l             0x2303 MACHPORT           r       an-- ---s u---- ----- ---- -v-  UI                  0 
xctest               77189     0x7ff958506d50  --l             0x2903 MACHPORT           r       an-- ---s u---- ----- ---- -v-  DF                  0 
johannes:~
$ lsof -p 77189
COMMAND   PID     USER   FD      TYPE             DEVICE SIZE/OFF                NODE NAME
xctest  77189 johannes    0r      CHR                3,2      0t0                 332 /dev/null
xctest  77189 johannes    1w      REG               1,14    47126          8747902795 /private/tmp/.nio-release-tools_1BTKsG/log_swift_dHHKIz
xctest  77189 johannes    2w      REG               1,14    47126          8747902795 /private/tmp/.nio-release-tools_1BTKsG/log_swift_dHHKIz
xctest  77189 johannes    3      PIPE 0x29ef7a3602bf2dad    16384                     ->0x3a9d0f9120b87c42
xctest  77189 johannes    4      PIPE 0x3a9d0f9120b87c42    16384                     ->0x29ef7a3602bf2dad
xctest  77189 johannes    5      PIPE 0x8558c6c1784f1f81    16384                     ->0x505cce4c58240e80
xctest  77189 johannes    6      PIPE 0x9192d1c71390c4f6    16384                     ->0x6f87bdc6ae091848
xctest  77189 johannes    7u   KQUEUE                                                 count=1, state=0x8
xctest  77189 johannes    8u   KQUEUE                                                 count=0, state=0xa
xctest  77189 johannes    9u    systm 0x7ee343f4177a7631      0t0                     [ctl com.apple.netsrc id 7 unit 70]
xctest  77189 johannes   10u   KQUEUE                                                 count=0, state=0xa
xctest  77189 johannes   11   NPOLICY                                                 
xctest  77189 johannes   12u    systm 0x7ee343f40c7e2f71      0t0                     [ctl com.apple.netsrc id 7 unit 63]
xctest  77189 johannes   13u     IPv4 0x7ee343f43bc24759      0t0                 TCP localhost:53708 (LISTEN)
xctest  77189 johannes   14u     IPv4 0x7ee343f40bb60ac9      0t0                 TCP localhost:53710->localhost:53708 (ESTABLISHED)
xctest  77189 johannes   15u     IPv4 0x7ee343f40bb61ef9      0t0                 TCP localhost:53708->localhost:53710 (ESTABLISHED)
xctest  77189 johannes   16u     unix 0x7ee343f3fb51f001      0t0                     ->0x7ee343f3fb51e061
xctest  77189 johannes   17u     IPv4 0x7ee343f40bb63d41      0t0                 TCP localhost:53711->localhost:53708 (ESTABLISHED)
xctest  77189 johannes   18u     IPv4 0x7ee343f40bb64759      0t0                 TCP localhost:53708->localhost:53711 (ESTABLISHED)
xctest  77189 johannes   19u     IPv4 0x7ee343f40bb84911      0t0                 TCP localhost:53712->localhost:53708 (ESTABLISHED)
xctest  77189 johannes   20u     IPv4 0x7ee343f40bb85d41      0t0                 TCP localhost:53708->localhost:53712 (ESTABLISHED)
xctest  77189 johannes   21u     IPv4 0x7ee343f40bb820b1      0t0                 TCP localhost:53713->localhost:53708 (ESTABLISHED)
xctest  77189 johannes   22u     IPv4 0x7ee343f40bb80269      0t0                 TCP localhost:53708->localhost:53713 (ESTABLISHED)
xctest  77189 johannes   23u     IPv4 0x7ee343f40bb8aef9      0t0                 TCP localhost:53714->localhost:53708 (ESTABLISHED)
xctest  77189 johannes   24u     IPv4 0x7ee343f40bb8a4e1      0t0                 TCP localhost:53715->localhost:53708 (ESTABLISHED)
xctest  77189 johannes   25u     IPv4 0x7ee343f40bb890b1      0t0                 TCP localhost:53708->localhost:53714 (ESTABLISHED)
xctest  77189 johannes   26u     IPv4 0x7ee343f40ba01d41      0t0                 TCP localhost:53716->localhost:53708 (ESTABLISHED)
xctest  77189 johannes   27u     IPv4 0x7ee343f40b9feac9      0t0                 TCP localhost:53708->localhost:53715 (ESTABLISHED)
xctest  77189 johannes   28u     IPv4 0x7ee343f40ba02759      0t0                 TCP localhost:53708->localhost:53716 (ESTABLISHED)
```

### LINKED ISSUE #263: testUncleanShutdownActuallyShutsDown  on macOS leads to assert(self.pool.count == 0) hit during shutdown
https://github.com/swift-server/async-http-client/blob/275502f482c3bf74ba130cd433c941f2affc595d/Sources/AsyncHTTPClient/HTTPClient.swift#L117

```
(lldb) p self
(AsyncHTTPClient.HTTPClient) $R8 = 0x0000000100d2d6b0 {
  eventLoopGroup = 0x0000000113c0efe0 {
    index = 0x0000000113c076a0 {}
    eventLoops = 1 value {
      [0] = 0x0000000113c0b150 {
        loop = 0x0000000113c11540 {
          baseOS_dispatch_queue@0 = {
            baseOS_dispatch_object@0 = {
              baseOS_object@0 = {
                baseNSObject@0 = {
                  isa = OS_dispatch_queue_serial
                }
              }
            }
          }
        }
        taskQueue = 0x0000000113d5d290 {
          baseOS_dispatch_queue@0 = {
            baseOS_dispatch_object@0 = {
              baseOS_object@0 = {
                baseNSObject@0 = {
                  isa = OS_dispatch_queue_serial
                }
              }
            }
          }
        }
        inQueueKey = 0x0000000100cc1c90 {}
        loopID = {}
        defaultQoS = {
          qosClass = <invalid> (0x2)
          relativePriority = 0
        }
        registeredChannels = 1 key/value pair {
          [0] = {
            key = (_value = 0x0000000100d30440)
            value = 0x0000000100d30440 {
              allocator = (malloc = 0x0000000111ced770 AsyncHTTPClientTests`@objc closure #1 (Swift.Int) -> Swift.Optional<Swift.UnsafeMutableRawPointer> in NIO.ByteBufferAllocator.init() -> NIO.ByteBufferAllocator at <compiler-generated>, realloc = 0x0000000111ced7e0 AsyncHTTPClientTests`@objc closure #2 (Swift.Optional<Swift.UnsafeMutableRawPointer>, Swift.Int) -> Swift.Optional<Swift.UnsafeMutableRawPointer> in NIO.ByteBufferAllocator.init() -> NIO.ByteBufferAllocator at <compiler-generated>, free = 0x0000000111ced830 AsyncHTTPClientTests`@objc closure #3 (Swift.Optional<Swift.UnsafeMutableRawPointer>) -> () in NIO.ByteBufferAllocator.init() -> NIO.ByteBufferAllocator at <compiler-generated>, memcpy = 0x0000000111ced8a0 AsyncHTTPClientTests`@objc closure #4 (Swift.UnsafeMutableRawPointer, Swift.UnsafeRawPointer, Swift.Int) -> () in NIO.ByteBufferAllocator.init() -> NIO.ByteBufferAllocator at <compiler-generated>)
              parent = nil
              tsEventLoop = 0x0000000113c0b150 {...}
              _pipeline = 0x0000000100d25e20 {
                head = 0x0000000100d2af50 {
                  next = 0x0000000100d2e2a0 {
                    next = nil
                    prev = 0x0000000100d2af50 {...}
                    pipeline = 0x0000000100d25e20 {...}
                    name = "tail"
                    inboundHandler = 0x0000000100b09fb0
                    outboundHandler = nil
                    removeHandlerInvoked = false
                    userTriggeredRemovalStarted = false
                  }
                  prev = nil
                  pipeline = 0x0000000100d25e20 {...}
                  name = "head"
                  inboundHandler = nil
                  outboundHandler = 0x0000000100b0a270
                  removeHandlerInvoked = false
                  userTriggeredRemovalStarted = false
                }
                tail = 0x0000000100d2e2a0 {...}
                idx = 0
                destroyed = false
                eventLoop = 0x0000000113c0b150 {...}
                _channel = 0x0000000100d30440 {...}
              }
              closePromise = {
                futureResult = 0x0000000100d1da30 {
                  _value = nil
                  eventLoop = 0x0000000113c0b150 {...}
                  _callbacks = {
                    firstCallback = nil
                    furtherCallbacks = nil
                  }
                }
              }
              nwConnection = 0x0000000102debb40 {
                endpoint = <invalid> (0x6c)
                parameters = 0x0000000102dd5720 {}
              }
              connectionQueue = 0x0000000100d18820 {
                baseOS_dispatch_queue@0 = {
                  baseOS_dispatch_object@0 = {
                    baseOS_object@0 = {
                      baseNSObject@0 = {
                        isa = OS_dispatch_queue_serial
                      }
                    }
                  }
                }
              }
              connectPromise = nil
              tcpOptions = 0x0000000100d2d9d0 {
                Network.NWProtocolOptions = {}
              }
              tlsOptions = nil
              state = inactive
              isActive0 = 0x0000000100d21200 {}
              supportedActivationType = connect
              outstandingRead = false
              options = (autoRead = true, supportRemoteHalfClosure = false, waitForActivity = true)
              pendingWrites = {
                _buffer = {
                  _buffer = {
                    _storage = 8 values {
                      [0] = nil
                      [1] = nil
                      [2] = nil
                      [3] = nil
                      [4] = nil
                      [5] = nil
                      [6] = nil
                      [7] = nil
                    }
                  }
                }
                headBackingIndex = 0
                tailBackingIndex = 0
              }
              backpressureManager = {
                writable = 0x0000000100d2f830 {}
                outstandingBytes = 0
                waterMarks = (low = 32768, high = 65536)
              }
              reuseAddress = false
              reusePort = false
              enablePeerToPeer = false
              _addressCache = {
                local = nil
                remote = nil
              }
              _addressCacheLock = 0x0000000100d367b0 (mutex = 0x0000000100d24060)
            }
          }
        }
        state = closing
      }
    }
  }
  eventLoopGroupProvider = shared {
    shared = 0x0000000113c0efe0 {...}
  }
  configuration = {
    tlsConfiguration = nil
    redirectConfiguration = {
      configuration = follow {
        follow = (max = 5, allowCycles = false)
      }
    }
    timeout = {
      connect = nil
      read = nil
    }
    maximumAllowedIdleTimeInConnectionPool = (nanoseconds = 60000000000)
    proxy = nil
    decompression = disabled
    ignoreUncleanSSLShutdown = false
  }
  pool = 0x0000000100d2c220 {
    configuration = {
      tlsConfiguration = nil
      redirectConfiguration = {
        configuration = follow {
          follow = (max = 5, allowCycles = false)
        }
      }
      timeout = {
        connect = nil
        read = nil
      }
      maximumAllowedIdleTimeInConnectionPool = (nanoseconds = 60000000000)
      proxy = nil
      decompression = disabled
      ignoreUncleanSSLShutdown = false
    }
    providers = 1 key/value pair {
      [0] = {
        key = {
          scheme = http
          host = "localhost"
          port = 59784
          unixPath = ""
        }
        value = 0x0000000100d3cc60 {
          configuration = {
            tlsConfiguration = nil
            redirectConfiguration = {
              configuration = follow {
                follow = (max = 5, allowCycles = false)
              }
            }
            timeout = {
              connect = nil
              read = nil
            }
            maximumAllowedIdleTimeInConnectionPool = (nanoseconds = 60000000000)
            proxy = nil
            decompression = disabled
            ignoreUncleanSSLShutdown = false
          }
          pool = 0x0000000100d2c220 {...}
          key = {
            scheme = http
            host = "localhost"
            port = 59784
            unixPath = ""
          }
          eventLoop = 0x0000000113c0b150 {...}
          lock = 0x0000000100d29780 (mutex = 0x0000000100d1bc60)
          closePromise = {
            futureResult = 0x0000000100d33aa0 {
              _value = success
              eventLoop = 0x0000000113c0b150 {...}
              _callbacks = {
                firstCallback = nil
                furtherCallbacks = nil
              }
            }
          }
          state = {
            maximumConcurrentConnections = 8
            eventLoop = 0x0000000113c0b150 {...}
            state = closed
            availableConnections = {
              _buffer = {
                _buffer = {
                  _storage = 1 value {
                    [0] = nil
                  }
                }
              }
              headBackingIndex = 0
              tailBackingIndex = 0
            }
            leasedConnections = 0 values {}
            waiters = {
              _buffer = {
                _buffer = {
                  _storage = 1 value {
                    [0] = nil
                  }
                }
              }
              headBackingIndex = 0
              tailBackingIndex = 0
            }
            openedConnectionsCount = 1
            pending = 0
          }
          backgroundActivityLogger = {
            handler = {}
            label = "AHC-do-not-log"
          }
        }
      }
    }
    lock = 0x0000000100d1ed90 (mutex = 0x0000000100d30d90)
    backgroundActivityLogger = {
      handler = {}
      label = "AHC-do-not-log"
    }
  }
  state = shutDown
  stateLock = 0x0000000100d1cf80 (mutex = 0x0000000100d21480)
}
```

```
(lldb) bt all
  thread #1, queue = 'com.apple.main-thread'
    frame #0: 0x00007fff70ff455e libsystem_kernel.dylib`__ulock_wait + 10
    frame #1: 0x00007fff70e58e29 libdispatch.dylib`_dlock_wait + 44
    frame #2: 0x00007fff70e590b7 libdispatch.dylib`_dispatch_group_wait_slow + 43
    frame #3: 0x00007fff70e5b1a1 libdispatch.dylib`dispatch_block_wait + 212
    frame #4: 0x00007fff709205c2 libswiftDispatch.dylib`Dispatch.DispatchWorkItem.wait() -> () + 34
    frame #5: 0x0000000111d6053f AsyncHTTPClientTests`EventLoopGroup.syncShutdownGracefully(self=0x0000000113c0efe0) at EventLoop.swift:762:22
    frame #6: 0x0000000111c15f60 AsyncHTTPClientTests`implicit closure #5 in HTTPClientTests.tearDown() at <compiler-generated>:0
    frame #7: 0x0000000111c15fd0 AsyncHTTPClientTests`partial apply for implicit closure #5 in HTTPClientTests.tearDown() at <compiler-generated>:0
    frame #8: 0x0000000111b97f5f AsyncHTTPClientTests`thunk for @callee_guaranteed () -> (@error @owned Error) at <compiler-generated>:0
    frame #9: 0x0000000111c15ff4 AsyncHTTPClientTests`thunk for @callee_guaranteed () -> (@error @owned Error)partial apply at <compiler-generated>:0
    frame #10: 0x0000000102f0db66 libXCTestSwiftSupport.dylib`closure #1 () throws -> () in XCTest.XCTAssertNoThrow<A>(_: @autoclosure () throws -> A, _: @autoclosure () -> Swift.String, file: Swift.StaticString, line: Swift.UInt) -> () + 54
    frame #11: 0x0000000102f0de15 libXCTestSwiftSupport.dylib`partial apply forwarder for closure #1 () throws -> () in XCTest.XCTAssertNoThrow<A>(_: @autoclosure () throws -> A, _: @autoclosure () -> Swift.String, file: Swift.StaticString, line: Swift.UInt) -> () + 21
    frame #12: 0x0000000102f0e0ab libXCTestSwiftSupport.dylib`partial apply forwarder for closure #1 () -> () in XCTest._XCTRunThrowableBlock(() throws -> ()) -> XCTest._XCTThrowableBlockResult + 27
    frame #13: 0x0000000102f0e101 libXCTestSwiftSupport.dylib`partial apply forwarder for reabstraction thunk helper from @callee_guaranteed () -> () to @escaping @callee_guaranteed () -> () + 17
    frame #14: 0x0000000102f0599e libXCTestSwiftSupport.dylib`reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @callee_unowned @convention(block) () -> () + 14
    frame #15: 0x0000000102f01d7a libXCTestSwiftSupport.dylib`_XCTRunThrowableBlockBridge + 42
    frame #16: 0x0000000102f057d0 libXCTestSwiftSupport.dylib`XCTest._XCTRunThrowableBlock(() throws -> ()) -> XCTest._XCTThrowableBlockResult + 208
    frame #17: 0x0000000102f0d6b6 libXCTestSwiftSupport.dylib`XCTest.XCTAssertNoThrow<A>(_: @autoclosure () throws -> A, _: @autoclosure () -> Swift.String, file: Swift.StaticString, line: Swift.UInt) -> () + 70
    frame #18: 0x0000000111c15734 AsyncHTTPClientTests`HTTPClientTests.tearDown(self=0x0000000113d19970) at HTTPClientTests.swift:73:9
    frame #19: 0x0000000111c1639b AsyncHTTPClientTests`@objc HTTPClientTests.tearDown() at <compiler-generated>:0
    frame #20: 0x000000010039a3b0 XCTest`-[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 179
    frame #21: 0x00000001003277ed XCTest`__51-[XCTestCase _performTearDownSequenceWithSelector:]_block_invoke + 131
    frame #22: 0x00000001003aacc0 XCTest`-[XCTContext _runActivityNamed:type:block:] + 301
    frame #23: 0x000000010033015e XCTest`-[XCTestCase startActivityWithTitle:type:block:] + 186
    frame #24: 0x0000000100330290 XCTest`-[XCTestCase startActivityWithTitle:block:] + 60
    frame #25: 0x0000000100326749 XCTest`-[XCTestCase _performTearDownSequenceWithSelector:] + 86
    frame #26: 0x0000000100325984 XCTest`-[XCTestCase invokeTest] + 1208
    frame #27: 0x00000001003272b2 XCTest`__26-[XCTestCase performTest:]_block_invoke_2 + 43
    frame #28: 0x000000010039a3b0 XCTest`-[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 179
    frame #29: 0x00000001003271e9 XCTest`__26-[XCTestCase performTest:]_block_invoke.362 + 86
    frame #30: 0x00000001003ab31d XCTest`+[XCTContext runInContextForTestCase:block:] + 211
    frame #31: 0x0000000100326a56 XCTest`-[XCTestCase performTest:] + 690
    frame #32: 0x000000010037848a XCTest`-[XCTest runTest] + 57
    frame #33: 0x00000001003202dd XCTest`__27-[XCTestSuite performTest:]_block_invoke + 329
    frame #34: 0x000000010031fafe XCTest`__59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
    frame #35: 0x00000001003ab31d XCTest`+[XCTContext runInContextForTestCase:block:] + 211
    frame #36: 0x000000010031fab5 XCTest`-[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
    frame #37: 0x000000010031fdb9 XCTest`-[XCTestSuite performTest:] + 290
    frame #38: 0x000000010037848a XCTest`-[XCTest runTest] + 57
    frame #39: 0x00000001003202dd XCTest`__27-[XCTestSuite performTest:]_block_invoke + 329
    frame #40: 0x000000010031fafe XCTest`__59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
    frame #41: 0x00000001003ab31d XCTest`+[XCTContext runInContextForTestCase:block:] + 211
    frame #42: 0x000000010031fab5 XCTest`-[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
    frame #43: 0x000000010031fdb9 XCTest`-[XCTestSuite performTest:] + 290
    frame #44: 0x000000010037848a XCTest`-[XCTest runTest] + 57
    frame #45: 0x00000001003202dd XCTest`__27-[XCTestSuite performTest:]_block_invoke + 329
    frame #46: 0x000000010031fafe XCTest`__59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
    frame #47: 0x00000001003ab31d XCTest`+[XCTContext runInContextForTestCase:block:] + 211
    frame #48: 0x000000010031fab5 XCTest`-[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
    frame #49: 0x000000010031fdb9 XCTest`-[XCTestSuite performTest:] + 290
    frame #50: 0x000000010037848a XCTest`-[XCTest runTest] + 57
    frame #51: 0x00000001003c76e2 XCTest`__44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke_2 + 148
    frame #52: 0x00000001003ab31d XCTest`+[XCTContext runInContextForTestCase:block:] + 211
    frame #53: 0x00000001003c7647 XCTest`__44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 111
    frame #54: 0x00000001003c77c8 XCTest`__44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.95 + 96
    frame #55: 0x0000000100346cc8 XCTest`-[XCTestObservationCenter _observeTestExecutionForBlock:] + 325
    frame #56: 0x00000001003c740d XCTest`-[XCTTestRunSession runTestsAndReturnError:] + 615
    frame #57: 0x0000000100303ea2 XCTest`-[XCTestDriver _runTests] + 466
    frame #58: 0x00000001003a74c1 XCTest`_XCTestMain + 108
    frame #59: 0x0000000100002ef7 xctest`main + 210
    frame #60: 0x00007fff70eb1cc9 libdyld.dylib`start + 1
    frame #61: 0x00007fff70eb1cc9 libdyld.dylib`start + 1
  thread #10
    frame #0: 0x00007fff70ff44ce libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff710b2aa1 libsystem_pthread.dylib`_pthread_wqthread + 390
    frame #2: 0x00007fff710b1b77 libsystem_pthread.dylib`start_wqthread + 15
* thread #11, queue = 'nio.transportservices.eventloop.taskqueue', stop reason = Assertion failed
    frame #0: 0x00007fff707cd380 libswiftCore.dylib`_swift_runtime_on_report
    frame #1: 0x00007fff70847243 libswiftCore.dylib`_swift_stdlib_reportFatalErrorInFile + 211
    frame #2: 0x00007fff7050e9de libswiftCore.dylib`closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 286
    frame #3: 0x00007fff7050e5e7 libswiftCore.dylib`closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 87
    frame #4: 0x00007fff7050ec21 libswiftCore.dylib`function signature specialization <Arg[1] = [Closure Propagated : closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never, Argument Types : [Swift.StaticStringSwift.UnsafeBufferPointer<Swift.UInt8>Swift.UIntSwift.UInt32]> of generic specialization <()> of Swift.String.withUTF8<A>((Swift.UnsafeBufferPointer<Swift.UInt8>) throws -> A) throws -> A + 257
    frame #5: 0x00007fff7050d1c0 libswiftCore.dylib`Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 528
  * frame #6: 0x00000001121e4cf5 AsyncHTTPClientTests`HTTPClient.deinit(self=0x0000000100d2d6b0) at HTTPClient.swift:117:9
    frame #7: 0x00000001121e4f39 AsyncHTTPClientTests`HTTPClient.__deallocating_deinit(self=0x0000000100d2d6b0) at HTTPClient.swift:0
    frame #8: 0x00007fff707cf1f0 libswiftCore.dylib`_swift_release_dealloc + 16
    frame #9: 0x00000001121f86dd AsyncHTTPClientTests`___lldb_unnamed_symbol1270$$AsyncHTTPClientTests + 29
    frame #10: 0x00007fff707cf1f0 libswiftCore.dylib`_swift_release_dealloc + 16
    frame #11: 0x00000001121f79eb AsyncHTTPClientTests`___lldb_unnamed_symbol1267$$AsyncHTTPClientTests + 1563
    frame #12: 0x00007fff707cf1f0 libswiftCore.dylib`_swift_release_dealloc + 16
    frame #13: 0x00000001121f8235 AsyncHTTPClientTests`___lldb_unnamed_symbol1268$$AsyncHTTPClientTests + 21
    frame #14: 0x00007fff707cf1f0 libswiftCore.dylib`_swift_release_dealloc + 16
    frame #15: 0x0000000111d74daa AsyncHTTPClientTests`___lldb_unnamed_symbol731$$AsyncHTTPClientTests + 42
    frame #16: 0x00007fff707cf1f0 libswiftCore.dylib`_swift_release_dealloc + 16
    frame #17: 0x0000000111d6923b AsyncHTTPClientTests`outlined consume of Swift.Optional<@escaping @callee_guaranteed () -> (@owned NIO.CallbackList)> + 27
    frame #18: 0x0000000111d6b7a8 AsyncHTTPClientTests`EventLoopPromise._resolve(value=failure, self=NIO.EventLoopPromise<AsyncHTTPClient.Connection> @ 0x0000700007cba028) at EventLoopFuture.swift:227:9
    frame #19: 0x0000000111d6ba75 AsyncHTTPClientTests`EventLoopPromise.fail(error=ioOnClosedChannel, self=NIO.EventLoopPromise<AsyncHTTPClient.Connection> @ 0x0000700007cba0c8) at EventLoopFuture.swift:180:14
    frame #20: 0x00000001121cbd3a AsyncHTTPClientTests`HTTP1ConnectionProvider.connect(result=failure, waiter=AsyncHTTPClient.HTTP1ConnectionProvider.Waiter @ 0x0000000100d35e68, closedConnection=nil, logger=Logging.Logger @ 0x0000000100d35e98, self=0x0000000100d3cc60) at ConnectionPool.swift:438:28
    frame #21: 0x00000001121c8e4a AsyncHTTPClientTests`closure #2 in HTTP1ConnectionProvider.execute(result=failure, self=0x0000000100d3cc60, waiter=AsyncHTTPClient.HTTP1ConnectionProvider.Waiter @ 0x0000000100d35e68, logger=Logging.Logger @ 0x0000000100d35e98) at ConnectionPool.swift:340:22
    frame #22: 0x00000001121c8cf1 AsyncHTTPClientTests`thunk for @escaping @callee_guaranteed (@guaranteed Result<Channel, Error>) -> () at <compiler-generated>:0
    frame #23: 0x0000000111d7266f AsyncHTTPClientTests`closure #1 in EventLoopFuture.whenComplete(callback=0x00000001121d2b80 AsyncHTTPClientTests`partial apply forwarder for reabstraction thunk helper from @escaping @callee_guaranteed (@guaranteed Swift.Result<NIO.Channel, Swift.Error>) -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Result<NIO.Channel, Swift.Error>) -> () at <compiler-generated>, self=0x0000000100d3cfc0) at EventLoopFuture.swift:738:13
    frame #24: 0x0000000111d698c0 AsyncHTTPClientTests`thunk for @escaping @callee_guaranteed () -> (@owned CallbackList) at <compiler-generated>:0
    frame #25: 0x0000000111d6a5d1 AsyncHTTPClientTests`thunk for @escaping @callee_guaranteed () -> (@owned CallbackList)partial apply at <compiler-generated>:0
    frame #26: 0x0000000111d6b013 AsyncHTTPClientTests`thunk for @escaping @callee_guaranteed () -> (@out CallbackList) at <compiler-generated>:0
    frame #27: 0x0000000111d6af37 AsyncHTTPClientTests`CallbackList._run(self=NIO.CallbackList @ 0x0000700007cbaa50) at EventLoopFuture.swift:107:28
    frame #28: 0x0000000111d6b795 AsyncHTTPClientTests`EventLoopPromise._resolve(value=failure, self=NIO.EventLoopPromise<()> @ 0x0000700007cbab68) at EventLoopFuture.swift:226:42
    frame #29: 0x0000000111d6ba75 AsyncHTTPClientTests`EventLoopPromise.fail(error=ioOnClosedChannel, self=NIO.EventLoopPromise<()> @ 0x0000700007cbac08) at EventLoopFuture.swift:180:14
    frame #30: 0x0000000112189c54 AsyncHTTPClientTests`NIOTSConnectionChannel.doClose0(error=ioOnClosedChannel, self=0x0000000100d30440) at NIOTSConnectionChannel.swift:574:28
    frame #31: 0x000000011218b229 AsyncHTTPClientTests`protocol witness for StateManagedChannel.doClose0(error:) in conformance NIOTSConnectionChannel at <compiler-generated>:0
    frame #32: 0x00000001121adae2 AsyncHTTPClientTests`StateManagedChannel.close0(error=ioOnClosedChannel, mode=all, promise=nil, self=0x0000000100d30440) at StateManagedChannel.swift:206:18
    frame #33: 0x000000011218b3b8 AsyncHTTPClientTests`protocol witness for ChannelCore.close0(error:mode:promise:) in conformance NIOTSConnectionChannel at <compiler-generated>:0
    frame #34: 0x0000000111d224b8 AsyncHTTPClientTests`HeadChannelHandler.close(context=0x0000000100d2af50, mode=all, promise=nil, self=0x0000000100b0a270) at ChannelPipeline.swift:970:38
    frame #35: 0x0000000111d227ed AsyncHTTPClientTests`protocol witness for _ChannelOutboundHandler.close(context:mode:promise:) in conformance HeadChannelHandler at <compiler-generated>:0
    frame #36: 0x0000000111d1e45f AsyncHTTPClientTests`ChannelHandlerContext.invokeClose(mode=all, promise=nil, self=0x0000000100d2af50) at ChannelPipeline.swift:1460:29
    frame #37: 0x0000000111d1c34c AsyncHTTPClientTests`ChannelPipeline.close0(mode=all, promise=nil, self=0x0000000100d25e20) at ChannelPipeline.swift:737:30
    frame #38: 0x0000000111d1c17c AsyncHTTPClientTests`ChannelPipeline.close(mode=all, promise=nil, self=0x0000000100d25e20) at ChannelPipeline.swift:637:13
    frame #39: 0x0000000111d07d1b AsyncHTTPClientTests`Channel.close(mode=all, promise=nil, self=0x0000000100d30440) at Channel.swift:209:18
    frame #40: 0x0000000112192921 AsyncHTTPClientTests`closure #1 in closure #1 in NIOTSEventLoop.closeGently(channel=0x0000000100d30440) at NIOTSEventLoop.swift:185:25
    frame #41: 0x0000000112192c3d AsyncHTTPClientTests`thunk for @callee_guaranteed (@unowned ObjectIdentifier, @guaranteed Channel) -> (@owned EventLoopFuture<()>, @error @owned Error) at <compiler-generated>:0
    frame #42: 0x0000000112192c94 AsyncHTTPClientTests`partial apply for thunk for @callee_guaranteed (@unowned ObjectIdentifier, @guaranteed Channel) -> (@owned EventLoopFuture<()>, @error @owned Error) at <compiler-generated>:0
    frame #43: 0x00007fff704ed505 libswiftCore.dylib`(extension in Swift):Swift.Collection.map<A>((A.Element) throws -> A1) throws -> Swift.Array<A1> + 757
    frame #44: 0x000000011219242b AsyncHTTPClientTests`closure #1 in NIOTSEventLoop.closeGently(self=0x0000000113c0b150, p=NIO.EventLoopPromise<Swift.Void> @ 0x0000700007cbb7d0) at NIOTSEventLoop.swift:184:76
    frame #45: 0x000000011218fd60 AsyncHTTPClientTests`thunk for @escaping @callee_guaranteed () -> () at <compiler-generated>:0
    frame #46: 0x00007fff70e576c4 libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #47: 0x00007fff70e58658 libdispatch.dylib`_dispatch_client_callout + 8
    frame #48: 0x00007fff70e5dc44 libdispatch.dylib`_dispatch_lane_serial_drain + 597
    frame #49: 0x00007fff70e5e609 libdispatch.dylib`_dispatch_lane_invoke + 414
    frame #50: 0x00007fff70e5daf6 libdispatch.dylib`_dispatch_lane_serial_drain + 263
    frame #51: 0x00007fff70e5e609 libdispatch.dylib`_dispatch_lane_invoke + 414
    frame #52: 0x00007fff70e67c09 libdispatch.dylib`_dispatch_workloop_worker_thread + 596
    frame #53: 0x00007fff710b2a3d libsystem_pthread.dylib`_pthread_wqthread + 290
    frame #54: 0x00007fff710b1b77 libsystem_pthread.dylib`start_wqthread + 15
  thread #12, queue = 'com.apple.network.connections'
    frame #0: 0x00007fff70ff2dfa libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x00007fff70ff3170 libsystem_kernel.dylib`mach_msg + 60
    frame #2: 0x00007fff710fd012 libxpc.dylib`_xpc_send_serializer + 96
    frame #3: 0x00007fff71101f58 libxpc.dylib`_xpc_pipe_simpleroutine + 79
    frame #4: 0x00007fff710fcf9a libxpc.dylib`xpc_pipe_simpleroutine + 42
    frame #5: 0x00007fff710d9a2b libsystem_trace.dylib`___os_activity_stream_reflect_block_invoke + 29
    frame #6: 0x00007fff70e58658 libdispatch.dylib`_dispatch_client_callout + 8
    frame #7: 0x00007fff70e5ad79 libdispatch.dylib`_dispatch_block_invoke_direct + 245
    frame #8: 0x00007fff70e5ac79 libdispatch.dylib`dispatch_block_perform + 124
    frame #9: 0x00007fff710d94d7 libsystem_trace.dylib`_os_activity_stream_reflect + 530
    frame #10: 0x00007fff710dd04e libsystem_trace.dylib`_os_log_impl_stream + 535
    frame #11: 0x00007fff710d184b libsystem_trace.dylib`_os_log_impl_flatten_and_send + 8502
    frame #12: 0x00007fff710d54b9 libsystem_trace.dylib`os_log_pack_send + 52
    frame #13: 0x00007fff6f8e32b1 libnetwork.dylib`nw_connection_log_event_summary_on_nw_queue + 433
    frame #14: 0x00007fff6f8e2f4e libnetwork.dylib`nw_connection_log_summary_on_nw_queue + 13790
    frame #15: 0x00007fff6f8df7ad libnetwork.dylib`nw_connection_send_stats_report_on_nw_queue + 2989
    frame #16: 0x00007fff6f8de0e8 libnetwork.dylib`__nw_connection_cancel_inner_block_invoke + 744
    frame #17: 0x00007fff70e576c4 libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #18: 0x00007fff70e58658 libdispatch.dylib`_dispatch_client_callout + 8
    frame #19: 0x00007fff70e5f909 libdispatch.dylib`_dispatch_workloop_invoke + 2161
    frame #20: 0x00007fff70e67c09 libdispatch.dylib`_dispatch_workloop_worker_thread + 596
    frame #21: 0x00007fff710b2a3d libsystem_pthread.dylib`_pthread_wqthread + 290
    frame #22: 0x00007fff710b1b77 libsystem_pthread.dylib`start_wqthread + 15
  thread #13
    frame #0: 0x00007fff710b1b68 libsystem_pthread.dylib`start_wqthread
  thread #14
    frame #0: 0x0000000000000000
  thread #15, name = 'NIO-ELT-201-#0'
    frame #0: 0x00007fff70ff7766 libsystem_kernel.dylib`kevent + 10
    frame #1: 0x0000000111e2e889 AsyncHTTPClientTests`@nonobjc kevent(_:_:_:_:_:_:) at <compiler-generated>:0
    frame #2: 0x0000000111e37068 AsyncHTTPClientTests`closure #1 in static KQueue.kevent(kq=9, changelist=nil, nchanges=0, eventlist=0x0000000101822000, nevents=64, timeout=nil) at System.swift:545:13
    frame #3: 0x0000000111e305e3 AsyncHTTPClientTests`thunk for @callee_guaranteed () -> (@unowned Int32, @error @owned Error) at <compiler-generated>:0
    frame #4: 0x0000000111e370d4 AsyncHTTPClientTests`thunk for @callee_guaranteed () -> (@unowned Int32, @error @owned Error)partial apply at <compiler-generated>:0
    frame #5: 0x0000000111e2efef AsyncHTTPClientTests`syscall<T>(blocking=false, function="kevent(kq:changelist:nchanges:eventlist:nevents:timeout:)", body=0x0000000111e370c0 AsyncHTTPClientTests`reabstraction thunk helper from @callee_guaranteed () -> (@unowned Swift.Int32, @error @owned Swift.Error) to @escaping @callee_guaranteed () -> (@out Swift.Int32, @error @owned Swift.Error)partial apply forwarder with unmangled suffix ".29" at <compiler-generated>) at System.swift:127:23
    frame #6: 0x0000000111e36eda AsyncHTTPClientTests`static KQueue.kevent(kq=9, changelist=nil, nchanges=0, eventlist=0x0000000101822000, nevents=64, timeout=nil, self=NIO.KQueue) at System.swift:544:20
    frame #7: 0x0000000111e002c7 AsyncHTTPClientTests`closure #1 in Selector.whenReady(ts=nil, self=0x0000000113d51470) at Selector.swift:518:28
    frame #8: 0x0000000111e0311f AsyncHTTPClientTests`partial apply for closure #1 in Selector.whenReady(strategy:_:) at <compiler-generated>:0
    frame #9: 0x0000000111e003c3 AsyncHTTPClientTests`thunk for @callee_guaranteed (@unowned UnsafePointer<timespec>?) -> (@unowned Int, @error @owned Error) at <compiler-generated>:0
    frame #10: 0x0000000111e03144 AsyncHTTPClientTests`partial apply for thunk for @callee_guaranteed (@unowned UnsafePointer<timespec>?) -> (@unowned Int, @error @owned Error) at <compiler-generated>:0
    frame #11: 0x0000000111ded487 AsyncHTTPClientTests`Optional.withUnsafeOptionalPointer<Wrapped>(body=0x0000000111e03130 AsyncHTTPClientTests`partial apply forwarder for reabstraction thunk helper from @callee_guaranteed (@unowned Swift.Optional<Swift.UnsafePointer<__C.timespec>>) -> (@unowned Swift.Int, @error @owned Swift.Error) to @escaping @callee_guaranteed (@unowned Swift.Optional<Swift.UnsafePointer<__C.timespec>>) -> (@out Swift.Int, @error @owned Swift.Error) at <compiler-generated>, self=nil) at Selector.swift:39:24
    frame #12: 0x0000000111dfdec5 AsyncHTTPClientTests`Selector.whenReady(strategy=block, body=0x0000000111debce0 AsyncHTTPClientTests`partial apply forwarder for reabstraction thunk helper from @callee_guaranteed (@guaranteed NIO.SelectorEvent<NIO.NIORegistration>) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed NIO.SelectorEvent<NIO.NIORegistration>) -> (@error @owned Swift.Error) at <compiler-generated>, self=0x0000000113d51470) at Selector.swift:517:34
    frame #13: 0x0000000111de79ea AsyncHTTPClientTests`closure #2 in SelectableEventLoop.run(self=0x0000000113d56b80, nextReadyTask=nil) at SelectableEventLoop.swift:395:36
    frame #14: 0x0000000111deba74 AsyncHTTPClientTests`partial apply for closure #2 in SelectableEventLoop.run() at <compiler-generated>:0
    frame #15: 0x0000000111cb621f AsyncHTTPClientTests`thunk for @callee_guaranteed () -> (@error @owned Error) at <compiler-generated>:0
    frame #16: 0x0000000111deba94 AsyncHTTPClientTests`thunk for @callee_guaranteed () -> (@error @owned Error)partial apply at <compiler-generated>:0
    frame #17: 0x0000000111de1c13 AsyncHTTPClientTests`closure #1 in withAutoReleasePool<T>(execute=0x0000000111deba80 AsyncHTTPClientTests`reabstraction thunk helper from @callee_guaranteed () -> (@error @owned Swift.Error) to @escaping @callee_guaranteed () -> (@out (), @error @owned Swift.Error)partial apply forwarder with unmangled suffix ".8" at <compiler-generated>) at SelectableEventLoop.swift:23:13
    frame #18: 0x0000000111de1c6f AsyncHTTPClientTests`partial apply for closure #1 in withAutoReleasePool<A>(_:) at <compiler-generated>:0
    frame #19: 0x00007fff70b65d8e libswiftObjectiveC.dylib`ObjectiveC.autoreleasepool<A>(invoking: () throws -> A) throws -> A + 46
    frame #20: 0x0000000111de1baa AsyncHTTPClientTests`withAutoReleasePool<T>(execute=0x0000000111deba80 AsyncHTTPClientTests`reabstraction thunk helper from @callee_guaranteed () -> (@error @owned Swift.Error) to @escaping @callee_guaranteed () -> (@out (), @error @owned Swift.Error)partial apply forwarder with unmangled suffix ".8" at <compiler-generated>) at SelectableEventLoop.swift:22:16
    frame #21: 0x0000000111de65db AsyncHTTPClientTests`SelectableEventLoop.run(self=0x0000000113d56b80) at SelectableEventLoop.swift:394:17
    frame #22: 0x0000000111d61396 AsyncHTTPClientTests`static MultiThreadedEventLoopGroup.runTheLoop(thread=0x0000000113d547d0, canEventLoopBeShutdownIndividually=false, selectorFactory=0x0000000111d61f60 AsyncHTTPClientTests`implicit closure #1 () throws -> NIO.Selector<NIO.NIORegistration> in NIO.MultiThreadedEventLoopGroup.init(numberOfThreads: Swift.Int) -> NIO.MultiThreadedEventLoopGroup at EventLoop.swift, initializer=0x0000000111d69130 AsyncHTTPClientTests`partial apply forwarder for reabstraction thunk helper from @escaping @callee_guaranteed (@in_guaranteed NIO.NIOThread) -> (@out ()) to @escaping @callee_guaranteed (@guaranteed NIO.NIOThread) -> () at <compiler-generated>, callback=0x0000000111d66d80 AsyncHTTPClientTests`partial apply forwarder for closure #1 (NIO.SelectableEventLoop) -> () in closure #1 (NIO.NIOThread) -> () in static NIO.MultiThreadedEventLoopGroup.(setupThreadAndEventLoop in _D5D78C61B22284700B9BD1ACFBC25157)(name: Swift.String, selectorFactory: () throws -> NIO.Selector<NIO.NIORegistration>, initializer: (NIO.NIOThread) -> ()) -> NIO.SelectableEventLoop at <compiler-generated>, self=NIO.MultiThreadedEventLoopGroup) at EventLoop.swift:822:22
    frame #23: 0x0000000111d61ba4 AsyncHTTPClientTests`closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(t=0x0000000113d547d0, selectorFactory=0x0000000111d61f60 AsyncHTTPClientTests`implicit closure #1 () throws -> NIO.Selector<NIO.NIORegistration> in NIO.MultiThreadedEventLoopGroup.init(numberOfThreads: Swift.Int) -> NIO.MultiThreadedEventLoopGroup at EventLoop.swift, initializer=0x0000000111d69130 AsyncHTTPClientTests`partial apply forwarder for reabstraction thunk helper from @escaping @callee_guaranteed (@in_guaranteed NIO.NIOThread) -> (@out ()) to @escaping @callee_guaranteed (@guaranteed NIO.NIOThread) -> () at <compiler-generated>, lock=(mutex = 0x0000000113d3ed60), _loop=0x0000000113d56b80, loopUpAndRunningGroup=0x0000000100cfb0c0) at EventLoop.swift:842:41
    frame #24: 0x0000000111d66cf3 AsyncHTTPClientTests`partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:selectorFactory:initializer:) at <compiler-generated>:0
    frame #25: 0x0000000111d6224f AsyncHTTPClientTests`thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () at <compiler-generated>:0
    frame #26: 0x0000000111e37841 AsyncHTTPClientTests`partial apply for thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () at <compiler-generated>:0
    frame #27: 0x0000000111e3e4ce AsyncHTTPClientTests`closure #1 in static ThreadOpsPosix.run($0=(_rawValue = 0x0000000113d507d0 -> 0x00007fff97558d58 libswiftCore.dylib`InitialAllocationPool + 51320)) at ThreadPosix.swift:105:13
    frame #28: 0x0000000111e3e609 AsyncHTTPClientTests`@objc closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) at <compiler-generated>:0
    frame #29: 0x00007fff710b6109 libsystem_pthread.dylib`_pthread_start + 148
    frame #30: 0x00007fff710b1b8b libsystem_pthread.dylib`thread_start + 15
```

### PR DESCRIPTION
**Pull request by artemredkin**
All internal connection flow should be executed when shutting down.

Motivation:
When we shut the client down, we expect the provider to finish all its tasks, if there are some, and then delete itself and succeed the close promise. Currently, if connection is created unsuccessfully, or available connection is closed/times out before we close it as part of shutdown, those connection will not trigger correct flow.

Modifications:
1. `connectFailed` now triggers correct flow when client is `.closed`
2. `timeout` now triggers correct flow when client is `.closed`
3. `removeClose` now triggers correct flow when client is `.closed`
4. `offer` is refactored
5. Added 4 new tests, that specifically test described scenarios

Result:
Closes #263 
Closes #260

### CODE REVIEW

File: Sources/AsyncHTTPClient/ConnectionPool.swift [hunk 1]
```diff
@@ -428,7 +419,15 @@ class HTTP1ConnectionProvider {
                 }
                 return self.state.offer(connection: connection)
             }
-            waiter.promise.succeed(connection)
+
+            switch action {
+            case .closeAnd:
+                // This happens when client was shut down during connect
```
Comment (weissi) [inline Sources/AsyncHTTPClient/ConnectionPool.swift:425]: I think we should log in the failure case, no?

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift [hunk 2]
```diff
@@ -1391,6 +1391,168 @@ class ConnectionPoolTests: XCTestCase {
...
+        var state = HTTP1ConnectionProvider.ConnectionsState(eventLoop: self.eventLoop)
+
+        XCTAssertTrue(state.enqueue())
+
+        let connectionPromise = self.eventLoop.makePromise(of: Connection.self)
+        let setupPromise = self.eventLoop.makePromise(of: Void.self)
+        let waiter = HTTP1ConnectionProvider.Waiter(promise: connectionPromise, setupComplete: setupPromise.futureResult, preference: .indifferent)
+        var action = state.acquire(waiter: waiter)
+
+        switch action {
```
Comment (weissi) [inline Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift:1406]: nit: you can write this a bit shorter as


```
guard case .create = action else {
    XCTFail("unexpected action \(action)")
    return
}
```

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift [hunk 3]
```diff
@@ -1391,6 +1391,168 @@ class ConnectionPoolTests: XCTestCase {
...
+            XCTAssertFalse(clean)
+        } else {
+            XCTFail("Expecting snapshot")
+        }
+
+        let connection = Connection(channel: EmbeddedChannel(), provider: self.http1ConnectionProvider)
+
+        action = state.offer(connection: connection)
+        switch action {
+        case .closeAnd(_, let next):
```
Comment (weissi) [inline Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift:1430]: isn't this

```
guard case .closeAnd(_, .closeProvider) = action else {
    XCTFail("unexpected action \(action)")
    return
}
```

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift [hunk 4]
```diff
@@ -1391,6 +1391,168 @@ class ConnectionPoolTests: XCTestCase {
...
+        var state = HTTP1ConnectionProvider.ConnectionsState(eventLoop: self.eventLoop)
+
+        XCTAssertTrue(state.enqueue())
+
+        let connectionPromise = self.eventLoop.makePromise(of: Connection.self)
+        let setupPromise = self.eventLoop.makePromise(of: Void.self)
+        let waiter = HTTP1ConnectionProvider.Waiter(promise: connectionPromise, setupComplete: setupPromise.futureResult, preference: .indifferent)
+        var action = state.acquire(waiter: waiter)
+
+        switch action {
```
Comment (weissi) [inline Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift:1456]: nit: this could be a `guard` too I think

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift [hunk 5]
```diff
@@ -1391,6 +1391,168 @@ class ConnectionPoolTests: XCTestCase {
...
+            XCTAssertTrue(waiters.isEmpty)
+            XCTAssertTrue(available.isEmpty)
+            XCTAssertTrue(leased.isEmpty)
+            XCTAssertFalse(clean)
+        } else {
+            XCTFail("Expecting snapshot")
+        }
+
+        action = state.connectFailed()
+        switch action {
```
Comment (weissi) [inline Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift:1477]: this too

File: Sources/AsyncHTTPClient/ConnectionPool.swift (hunk 1 above)
Comment (artemredkin) [reply Sources/AsyncHTTPClient/ConnectionPool.swift:425]: good idea, done!

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift (hunk 2 above)
Comment (artemredkin) [reply Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift]: 👍

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift (hunk 3 above)
Comment (artemredkin) [reply Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift]: 👍

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift (hunk 4 above)
Comment (artemredkin) [reply Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift]: 👍

File: Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift (hunk 5 above)
Comment (artemredkin) [reply Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift]: 👍
